ansible-collections/servicenow.itsm

.github/workflows/ansible-test.yml

Up until now, the collection has only been tested on ansible-base 2.10. Now that we got over the initial experimentation phase, it is time to ramp the testing up a notch.

Expand testing matrix

---

plugins/module_utils/utils.py
tests/unit/plugins/module_utils/test_utils.py

Newly added function checks if one dictionary is a superset of key-value pairs of the other dictionary. This check will be the basis of our change detection.

Add is_superset utility predicate

---

plugins/modules/incident.py
tests/integration/targets/incident/tasks/main.yml

Complete incident module

---

.flake8
Makefile
changelogs/config.yaml
docs/hacking.md
docs/module_template.md
docs/unit_testing.md
plugins/doc_fragments/instance.py
plugins/doc_fragments/number.py
plugins/doc_fragments/sys_id.py
plugins/module_utils/arguments.py
plugins/module_utils/client.py
plugins/module_utils/errors.py
plugins/module_utils/table.py
plugins/module_utils/utils.py
plugins/modules/change_request_info.py
plugins/modules/incident.py
plugins/modules/incident_info.py
plugins/modules/problem_info.py
tests/unit/plugins/conftest.py
tests/unit/plugins/module_utils/test_arguments.py
tests/unit/plugins/module_utils/test_client.py
tests/unit/plugins/module_utils/test_table.py
tests/unit/plugins/module_utils/test_utils.py
tests/unit/plugins/modules/test_change_request_info.py
tests/unit/plugins/modules/test_incident_info.py
tests/unit/plugins/modules/test_problem_info.py

* Make 160 characters limit for flake8
* Consider raw formatting for DOCUMENTATION, EXAMPLES, and RETURN
* Introduce Changelog configuration for the antsibullbot
* Remove deprecated ANSIBLE_METADATA
* Adjust copyright boilerplate
* Misc typo fixes
changelogs/config.yaml
plugins/modules/incident.py
plugins/modules/incident_info.py
plugins/modules/problem_info.py

Misc doc changes

---

README.md
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.problem_info_module.rst

* Update README.md
* Added rst based documentation for the modules
README.md
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.problem_info_module.rst

Update readme file

---

plugins/modules/incident.py

* Check if caller value is provided or not
plugins/modules/incident.py

incident: check if caller is specified

---

plugins/module_utils/incident.py
plugins/modules/incident.py
plugins/modules/incident_info.py
tests/integration/targets/incident/tasks/main.yml

Payload fields mapping

---

plugins/module_utils/change_request.py
plugins/module_utils/table.py
plugins/modules/change_request.py
plugins/modules/change_request_info.py
tests/integration/targets/change_request/tasks/main.yml

Add change request module

---

plugins/doc_fragments/number.py
plugins/doc_fragments/sys_id.py
plugins/modules/change_request.py
plugins/modules/incident.py
plugins/modules/problem.py

Make sure our regular modules use non-info document fragments.

Update doc fragments

---

plugins/module_utils/table.py
plugins/modules/change_request.py
tests/integration/targets/change_request/tasks/main.yml

Fix for standard change request

---

plugins/modules/change_request.py
plugins/modules/incident.py
tests/integration/targets/change_request/tasks/main.yml
tests/integration/targets/incident/tasks/main.yml

Changes in this PR just deduplicate the validation code that is now part of the utility function.
/cc @mdolin

Reuse validation helper

---

plugins/module_utils/configuration_item.py
plugins/modules/configuration_item.py
tests/integration/targets/configuration_item/tasks/main.yml

Resolves #8.
We add the `configuration_item` module that manages records in the base ServiceNow configuration item table, `cmdb_ci`.

Configuration item module

---

plugins/module_utils/configuration_item.py
plugins/modules/configuration_item.py
plugins/modules/configuration_item_info.py
tests/integration/targets/configuration_item/tasks/main.yml

Add configuration item info module

---

README.md
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.servicenow.itsm.now_inventory.rst

* Added docs for configuration_item_info
* Added docs for configuration_item
* Updated rest of the docs for minor changes
README.md
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.servicenow.itsm.now_inventory.rst

Minor doc update

---

tests/unit/plugins/modules/test_incident.py

Add unit tests for incident module

---

tests/unit/plugins/modules/test_change_request.py

Add unit tests for change request

---

tests/unit/plugins/modules/test_problem.py

Add unit tests for problem module

---

tests/unit/plugins/modules/test_configuration_item.py
tests/unit/plugins/modules/test_configuration_item_info.py

Configuration item unit tests

---

README.md
docs/servicenow.itsm.table_info_module.rst
plugins/modules/table_info.py
tests/unit/plugins/modules/test_table_info.py

* Module to list all tables and related information
README.md
docs/servicenow.itsm.table_info_module.rst
plugins/modules/table_info.py
tests/unit/plugins/modules/test_table_info.py

table_info: Add new module

---

CHANGELOG.rst
LICENSE
changelogs/changelog.yaml
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.servicenow.itsm.now_inventory.rst
galaxy.yml
plugins/inventory/now.py
plugins/modules/change_request.py
plugins/modules/configuration_item.py
plugins/modules/configuration_item_info.py
plugins/modules/incident.py
plugins/modules/problem.py

CHANGELOG.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.servicenow.itsm.now_inventory.rst
galaxy.yml
plugins/modules/change_request.py
plugins/modules/configuration_item.py
plugins/modules/configuration_item_info.py
plugins/modules/incident.py
plugins/modules/problem.py

Release 1.0.0

---

changelogs/fragments/filter_results.yml
plugins/doc_fragments/query.py
plugins/module_utils/arguments.py
plugins/module_utils/query.py
plugins/modules/change_request_info.py
plugins/modules/configuration_item_info.py
plugins/modules/incident_info.py
plugins/modules/problem_info.py
tests/integration/targets/change_request/tasks/main.yml
tests/integration/targets/configuration_item/tasks/main.yml
tests/integration/targets/incident/tasks/main.yml
tests/integration/targets/problem/tasks/main.yml
tests/unit/plugins/module_utils/test_query.py
tests/unit/plugins/modules/test_change_request_info.py
tests/unit/plugins/modules/test_configuration_item_info.py
tests/unit/plugins/modules/test_incident_info.py
tests/unit/plugins/modules/test_problem_info.py

Add query module utils to filter the results

---

changelogs/fragments/inventory_host.yml
plugins/inventory/now.py
plugins/module_utils/client.py
tests/unit/plugins/module_utils/test_client.py
tests/unit/plugins/modules/test_change_request_info.py
tests/unit/plugins/modules/test_configuration_item.py
tests/unit/plugins/modules/test_configuration_item_info.py
tests/unit/plugins/modules/test_incident_info.py
tests/unit/plugins/modules/test_problem_info.py

Add checks for instance host value before making
REST calls from `Client`.
changelogs/fragments/inventory_host.yml

now - Check instance host value

---

CHANGELOG.rst
README.md
changelogs/changelog.yaml
changelogs/fragments/filter_results.yml
changelogs/fragments/inventory_host.yml
changelogs/fragments/refresh_token.yml
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.problem_info_module.rst
galaxy.yml

CHANGELOG.rst
README.md
changelogs/fragments/filter_results.yml
changelogs/fragments/inventory_host.yml
changelogs/fragments/refresh_token.yml
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.problem_info_module.rst
galaxy.yml

Release 1.1.0

---

plugins/module_utils/table.py
tests/unit/plugins/module_utils/test_table.py

By default, ServiceNow table API only returns the first 1000 records when queried. This commit makes sure we retrieve all of the records even if there are more than 1000 of them.

Add pagination support to table client

---

plugins/inventory/now.py
tests/integration/targets/inventory/files/constructed.yml
tests/integration/targets/inventory/playbooks/constructed.yml
tests/unit/plugins/inventory/test_now.py

The current set of changes add support for constructed changes to the inventory plugin.
Fixes https://github.com/ansible-collections/servicenow.itsm/issues/35
Inventory plugin

Add supprt for constructed features

---

changelogs/fragments/now_construct_inventory.yml
plugins/inventory/now.py

changelogs/fragments/now_construct_inventory.yml

Add missing changelog for constructed feature

---

changelogs/fragments/lowercase-response-headers.yaml
plugins/module_utils/client.py
plugins/module_utils/table.py
tests/unit/plugins/module_utils/test_client.py

Response headers now have lowercase keys for better consistency across different Python versions.
- client

Lowercase response headers

---

test-requirements.txt

selinux-please-lies-to-me should be enough for our needs.

we don't need selinux to run the tests

---

plugins/modules/configuration_item_batch.py

plugins/modules/configuration_item_batch.py

Misc typo in example

---

docs/general_usage_patterns.md

Change Ansible Tower to Automation Controller to reflect changes in AAP 2.
General usage patterns doc update

changing Tower to Controller

---

plugins/inventory/now.py
plugins/module_utils/arguments.py
plugins/module_utils/attachment.py
plugins/module_utils/client.py
plugins/module_utils/query.py
plugins/modules/change_request_info.py
plugins/modules/configuration_item_info.py
plugins/modules/incident_info.py
plugins/modules/problem_info.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.9.txt
tests/unit/plugins/module_utils/test_attachment.py
tests/unit/plugins/module_utils/test_client.py
tests/unit/plugins/module_utils/test_query.py
tests/unit/plugins/modules/test_change_request_info.py
tests/unit/plugins/modules/test_configuration_item.py
tests/unit/plugins/modules/test_configuration_item_info.py
tests/unit/plugins/modules/test_incident_info.py
tests/unit/plugins/modules/test_problem_info.py

Example of code, that succesfully passes sanity test.
Performed actions:
- Added a skip for checking colon operator inside python [::].
- fixing disagrement between black, pep8, pycodetest
- as example only for ansible 2.12, can be added for others
- Commented out unused files.
- Executed make format
```paste below
```

Fixed sanity test

---

README.md
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
plugins/inventory/now.py

README.md
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst

Doc updates

---

plugins/doc_fragments/configuration_item_mapping.py
plugins/doc_fragments/problem_mapping.py
plugins/module_utils/arguments.py
plugins/modules/configuration_item.py
plugins/modules/configuration_item_info.py
plugins/modules/problem.py
plugins/modules/problem_info.py

Mapping for incident and problem. This should be last in existing codebase. Will fix PR-s after.
```paste below
```

Mapping config and problem

---

galaxy.yml

Update Galaxy tags

---

CHANGELOG.rst
changelogs/changelog.yaml

A patch release for ServiceNow ITSM collection
CHANGELOG.rst

Release 1.3.1

---

CHANGELOG.rst
changelogs/changelog.yaml

This is the patch release of the ``servicenow.itsm`` collection.
CHANGELOG.rst

Release 1.3.2

---

CHANGELOG.rst
changelogs/changelog.yaml

This is the patch release of the servicenow.itsm collection
CHANGELOG.rst

Release 1.3.3

---

changelogs/fragments/ignore_2.14.yml
tests/sanity/ignore-2.14.txt

Address CI tests for 2.14.0.dev0
changelogs/fragments/ignore_2.14.yml
tests/sanity/ignore-2.14.txt

Copy ignore-2.13.txt to ignore-2.14.txt

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/ignore_2.14.yml
changelogs/fragments/inventory_grant.yaml
changelogs/fragments/mapping.yml
changelogs/fragments/now_inv_docs.yaml
changelogs/fragments/validate.yml
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_module.rst

This is the minor release of the servicenow.itsm collection
CHANGELOG.rst
changelogs/fragments/ignore_2.14.yml
changelogs/fragments/inventory_grant.yaml
changelogs/fragments/mapping.yml
changelogs/fragments/validate.yml
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_module.rst

Release 1.4.0

---

changelogs/fragments/attachment_integration_tests_missing_register_variables.yml
tests/integration/targets/attachment/tasks/main.yml

Add missing register variables
Bugfix Pull Request
Attachment integration test (main.yml)

Fix attachment integration tests bugs - missing register variable

---

changelogs/fragments/179_encode_servicenow_rest_api_module_in_ansible.yml
plugins/module_utils/api.py
plugins/module_utils/utils.py
plugins/modules/api.py
plugins/modules/api_info.py
tests/integration/targets/api/tasks/main.yml
tests/unit/plugins/modules/test_api.py
tests/unit/plugins/modules/test_api_info.py

This PR is equivalent to https://github.com/ansible-collections/servicenow.itsm/pull/179, with only difference being the branch on which this PR is being pushed on.
For further info, please refer to https://github.com/ansible-collections/servicenow.itsm/pull/179.

Raw API module: Basic

---

docs/user_mapping.md

Added manual how to use user mapping inside playbooks.
User mapping
```paste below
```

[bp/1.4]: Added user maping doc

---

CHANGELOG.rst
changelogs/changelog.yaml
docs/servicenow.itsm.now_inventory.rst
docs/user_mapping.md
galaxy.yml
plugins/module_utils/query.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.9.txt

This is the minor release of the ``servicenow.itsm`` collection.
CHANGELOG.rst
docs/user_mapping.md
galaxy.yml
plugins/module_utils/query.py

Release 1.4.1

---

README.md

Update readme with Release table

---

changelogs/fragments/problem_mapping_bugix.yml
plugins/module_utils/utils.py
plugins/modules/api.py
plugins/modules/api_info.py
plugins/modules/problem.py
test-requirements.txt
tests/integration/targets/problem_with_mapping/tasks/main.yml
tests/unit/plugins/modules/test_problem.py

Mapping was broken just before release of 2.0.0. This fixes it.
Fixes #220 
```paste below
```

Problem mapping bugfix

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/api_query_params.yml
changelogs/fragments/inventory_plugin_bugfix.yml
changelogs/fragments/inventory_plugin_reference_fields.yml
changelogs/fragments/problem_mapping_bugix.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.now_inventory.rst
galaxy.yml

This is the minor release of the servicenow.itsm collection.
CHANGELOG.rst
changelogs/fragments/api_query_params.yml
changelogs/fragments/inventory_plugin_bugfix.yml
changelogs/fragments/inventory_plugin_reference_fields.yml
changelogs/fragments/problem_mapping_bugix.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
galaxy.yml

Release 2.1.0

---

CHANGELOG.rst
README.md
changelogs/changelog.yaml
changelogs/fragments/attachment_upload_module.yaml
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
galaxy.yml

This is the minor release of the servicenow.itsm collection
CHANGELOG.rst
changelogs/fragments/attachment_upload_module.yaml
galaxy.yml

Release 2.2.0

---

README.md
scripts/prepare_release.yml

Automate release process
README.md
tools/prepare_release.yml

Automate release process with Ansible

---

docs/general_usage_patterns.md

SN_HOST value must start with https://.
Fixes: #267
docs/general_usage_patterns.md

Add a note SN_HOST

---

plugins/action/api.py
plugins/inventory/now.py
plugins/module_utils/attachment.py
plugins/module_utils/query.py
plugins/module_utils/table.py
plugins/modules/attachment_upload.py

plugins/action/api.py
plugins/module_utils/attachment.py
plugins/module_utils/query.py
plugins/module_utils/table.py
plugins/modules/attachment_upload.py

code formatting to make black happy

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/261_fix_env_variable.yml
changelogs/fragments/attachment_upload_module_bugfix.yml
changelogs/fragments/client_access_token.yaml
changelogs/fragments/client_validate_certs.yaml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
galaxy.yml

CHANGELOG.rst
changelogs/fragments/.gitkeep
changelogs/fragments/261_fix_env_variable.yml
changelogs/fragments/attachment_upload_module_bugfix.yml
changelogs/fragments/client_access_token.yaml
changelogs/fragments/client_validate_certs.yaml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst …

prepare 2.3.0 release

---

.github/workflows/all_green_check.yml
.github/workflows/unit_source.yml
.github/workflows/units.yml

Added unit tests

---

plugins/modules/configuration_item_info.py

Add doc for configuration_item_info with mapping

---

tests/integration/targets/configuration_item/tasks/main.yml

This commit adds integration tests for PR#208.
Fixes #208
- Missing integration tests

Add integration tests for #208

---

changelogs/fragments/update_prepare_release.yml
scripts/prepare_release.yml

* Use antsibull-docs instead of collection_prep
* Keep .gitkeep file

Update release script

---

changelogs/fragments/inventory.yml
plugins/inventory/now.py
tests/integration/targets/inventory/files/cache.now.yml
tests/integration/targets/inventory/playbooks/cache.yml

Add cache support for inventory module.
Fixes #176

Add cache support for inventory plugin

---

plugins/inventory/now.py
plugins/module_utils/api.py
plugins/module_utils/generic.py
plugins/modules/api_info.py
plugins/modules/configuration_item_info.py
tests/integration/targets/api/tasks/main.yml
tests/integration/targets/api/templates/test_template_patch.j2
tests/integration/targets/api_generic/tasks/main.yml
tests/unit/plugins/module_utils/test_client.py

Minor typo fixes

---

.github/workflows/all_green_check.yml
.github/workflows/integration.yml
.github/workflows/integration_source.yml

This PR adds integration tests actions.
It expects 3 secrets:
- SN_HOST
- SN_USERNAME
- SN_PASSWORD

Add integration tests actions

---

.github/workflows/integration_source.yml

This PR adds the following integration tests to workflow:
- api_generic
- attachment
- attachment_info
- attachment_upload
- change_request

Add more integration test to workflows

---

.github/workflows/integration_source.yml

Now that upstream servicenow instances have been provisioned, we can connect them to the github workflows. The variables have been created in the repo, and this PR links them.
GitHub Workflows

Include other servicenow versions in matrix

---

tests/integration/targets/configuration_item_batch/tasks/main.yml

This PR fixes integration tests for `configuration_items_batch`. 
The test was falling because was not self-contained. 

fix failing test when calling multiple times

---

tests/integration/targets/change_request_task/tasks/main.yml
tests/integration/targets/configuration_item/tasks/main.yml

Fix failing `change_request_task` integration tests

Fix failing `change_request_task` integration tests

---

changelogs/fragments/release_summary.yml

Add release summary for 2.5.0

---

.github/workflows/integration_source.yml
.github/workflows/unit_source.yml
changelogs/fragments/galaxy_update.yml
changelogs/fragments/workflow_update.yml
galaxy.yml
meta/runtime.yml

Update metadata in accordance with Ansible Lifecycle policy. This also means dropping Python 3.9 from the text matrix.
While here, update authors metadata in galaxy.yml.
Galaxy metadata and github workflows

Update some metadata

---

changelogs/fragments/inventory_bug.yml

Fragment doc for #360 
inventory

add fragment for inventory crash bug fix

---

changelogs/fragments/inventory_bug.yml

Fix the section name for inventory bug.
inventory

Fix section name for inventory bug fragment doc

---

.github/workflows/linters.yml
.github/workflows/tox.yml

Fixes #344 
We will carry a local tox.yml briefly but propose it upstream to ansible-networking and then switch to that version when/if they accept it

Update tox linter to optionally take checkout parameters

---

.github/workflows/linters.yml

DO NOT Merge - Test empty commit

---

.github/workflows/tox.yml

Workflow fixes

---

.github/workflows/linters.yml
.github/workflows/tox.yml

Correct Tox workflow for linters

---

tests/unit/plugins/module_utils/test_attachment.py

Fix lint issue on main

---

changelogs/fragments/release_summary.yml

Create release summary for 2.6.0

Create release summary for forthcoming 2.6.0

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/galaxy_update.yml
changelogs/fragments/handle_duplicate_records.yml
changelogs/fragments/inventory_bug.yml
changelogs/fragments/release_summary.yml
changelogs/fragments/workflow_update.yml
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
galaxy.yml

prepare 2.6.0 release

---

README.md

Update README module's list
README.md

Update readme following last release

---

.ansible-lint
changelogs/fragments/fix_documentation.yml
changelogs/fragments/release_summary.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
docs/servicenow.itsm.service_catalog_module.rst
plugins/modules/attachment_upload.py

Fix docs for 2.6.0

---

README.md

Fix README's  modules table

---

changelogs/fragments/fix_service_catalog_enndpoint.yml
plugins/module_utils/service_catalog.py
tests/unit/plugins/modules/test_service_catalog.py

Updated the service catalogue module to consume the submit_order endpoint

Changed the submit_order endpoint for issue #394

---

changelogs/fragments/release_summary.yml

Prep for 2.6.2 release
Add release summary

Prep for 2.6.2 release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/fix_service_catalog_enndpoint.yml
changelogs/fragments/release_summary.yml
changelogs/fragments/remove_sanity_test_matrix.yml
changelogs/fragments/remove_tokyo.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
docs/servicenow.itsm.service_catalog_module.rst
galaxy.yml

Run the dev prep script
Release

prepare 2.6.2 release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/fix_service_catalog_enndpoint.yml
changelogs/fragments/release_summary.yml
changelogs/fragments/remove_sanity_test_matrix.yml
changelogs/fragments/remove_tokyo.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
docs/servicenow.itsm.service_catalog_module.rst
galaxy.yml

Fix version number in galaxy.yml

Fix galaxy.yml version number

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/release_summary.yml
galaxy.yml

prepare 2.6.3 release

---

.github/workflows/integration_source.yml
changelogs/fragments/add_xanadu.yaml

Add ServiceNow Xanadu to test matrix
tests
Have added necessary secrets to repo configuration.
Have upgraded one test instance to Xanadu.

Add Xanadu to test matrix

---

.github/workflows/integration_source.yml

Add problem int tests to workflow.
To be merged after the API Red Hat Ansible Automation Content App is fixed.

Add problem int tests to workflow

---

tests/integration/targets/problem/tasks/main.yml
tests/integration/targets/problem_task/tasks/main.yml
tests/integration/targets/problem_with_mapping/tasks/main.yml

Fix integration tests for problem modules to be executed in parallel. 

Fix integration tests for problem

---

changelogs/fragments/update_release_script.yml
scripts/prepare_release.yml

Update release machinery as title
Release mechanism

Update release script to allow testrun and do additional validation

---

changelogs/fragments/fix_integration_tests.yml
changelogs/fragments/query_limiting.yml
changelogs/fragments/release_summary.yml
changelogs/fragments/update_release_script.yml

Add links to docs and release summary in prep for 2.8.0
Docs

Update docs links and add release summary

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/fix_integration_tests.yml
changelogs/fragments/query_limiting.yml
changelogs/fragments/release_summary.yml
changelogs/fragments/update_release_script.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
docs/servicenow.itsm.service_catalog_module.rst
galaxy.yml

prepare 2.8.0 release

---

.github/workflows/integration_source.yml
.github/workflows/unit_source.yml
changelogs/fragments/20250416-integration_source.yaml

1. Removing support in ansible-version 2.14
2. Adding support in ansible-version 2.18, python version 3.11
3. Adding support in ansible-version 2.18, python version 3.12
4. Adding support in ansible-version 2.18, python version 3.13
.github/workflows/integration_source.yml

Updating github workflows:

---

.github/workflows/integration_source.yml
.github/workflows/unit_source.yml

Might misunderstand the issue, just testing.
```paste below
```

Remove 3.10 from milestone and devel targets

---

.github/workflows/all_green_check.yml
changelogs/fragments/434-add-nightly-workflow.yaml

Add a trigger to run the main testing workflow nightly

add nightly workflow trigger

---

README.md

- Updated structure and formatting
- Added required sections: Requirements, Use Cases, Testing, Support, etc.
- Ensured all links use full URLs
Readme.md

Refactor README to  official documentation template

---

changelogs/fragments/446-reduce-complexity.yaml
plugins/inventory/now.py
plugins/modules/change_request_task_info.py

Reduces the complexity of two functions by breaking them up into smaller functions. This is so the linting workflow will pass. 
plugins/inventory/now
plugins/modules/change_request_task_info

reduce function complexity for linters

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/291_release_summary.yml
changelogs/fragments/451-inventory-bugfix.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
docs/servicenow.itsm.service_catalog_module.rst
galaxy.yml

prepare 2.9.1 release

---

changelogs/fragments/457-obtain-records.yml
changelogs/fragments/460-inventory-on-219.yml
changelogs/fragments/release_summary.yml

Document issue fix and known issue for 2.9.3-to-be
Release

Create additional docs for upcoming 2.9.3

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/457-obtain-records.yml
changelogs/fragments/458-refactor-inventory-tests.yml
changelogs/fragments/460-inventory-on-219.yml
changelogs/fragments/release_summary.yml
docs/servicenow.itsm.api_info_module.rst
docs/servicenow.itsm.api_module.rst
docs/servicenow.itsm.attachment_info_module.rst
docs/servicenow.itsm.attachment_upload_module.rst
docs/servicenow.itsm.change_request_info_module.rst
docs/servicenow.itsm.change_request_module.rst
docs/servicenow.itsm.change_request_task_info_module.rst
docs/servicenow.itsm.change_request_task_module.rst
docs/servicenow.itsm.configuration_item_batch_module.rst
docs/servicenow.itsm.configuration_item_info_module.rst
docs/servicenow.itsm.configuration_item_module.rst
docs/servicenow.itsm.configuration_item_relations_info_module.rst
docs/servicenow.itsm.configuration_item_relations_module.rst
docs/servicenow.itsm.incident_info_module.rst
docs/servicenow.itsm.incident_module.rst
docs/servicenow.itsm.now_inventory.rst
docs/servicenow.itsm.problem_info_module.rst
docs/servicenow.itsm.problem_module.rst
docs/servicenow.itsm.problem_task_info_module.rst
docs/servicenow.itsm.problem_task_module.rst
docs/servicenow.itsm.service_catalog_info_module.rst
docs/servicenow.itsm.service_catalog_module.rst
galaxy.yml

prepare 2.9.3 release

---

.github/workflows/integration_source.yml

Typo in the OAUTH secret names in the GHA. This should fix that

fix references to oauth secret in gha

---

Makefile
changelogs/fragments/487-add-catalog-request-module.yml
plugins/doc_fragments/catalog_request_mapping.py
plugins/module_utils/arguments.py
plugins/modules/catalog_request.py
tests/integration/targets/itsm_catalog_request/meta/main.yml
tests/integration/targets/itsm_catalog_request/tasks/main.yml
tests/unit/plugins/modules/test_catalog_request.py

Adds the catalog_requests module to allow users to manage catalog requests in service now
catalog_requests

add module to manage catalog requests

---

README.md
changelogs/fragments/490-add-catalog-request-task-module.yml
plugins/doc_fragments/catalog_request_task_mapping.py
plugins/inventory/now.py
plugins/module_utils/arguments.py
plugins/module_utils/catalog_request_task.py
plugins/modules/catalog_request_task.py
tests/integration/targets/itsm_catalog_request_task/meta/main.yml
tests/integration/targets/itsm_catalog_request_task/tasks/main.yml
tests/unit/plugins/modules/test_catalog_request_task.py

Add new module to manage catalog request tasks
catalog_request_task

add catalog_request_task module

---

README.md
changelogs/fragments/488-add-catalog-request-info-module.yml
plugins/modules/catalog_request_info.py
tests/integration/targets/itsm_catalog_request/tasks/main.yml
tests/unit/plugins/modules/test_catalog_request_info.py

Adds the catalog_request_info module to gather info about catalog requests
catalog_request_info

add catalog_request_info module

---

.github/workflows/integration_source.yml
.github/workflows/unit_source.yml
changelogs/fragments/20250821-fix-linter-error.yml
extensions/eda/plugins/event_source/records.py

Fix black issue by reformatting event_source.py
Exclude python 3.11 from milestone and devel unit tests

Fix CICD issues

---

changelogs/fragments/497-fix-eda-example.yml
extensions/eda/plugins/event_source/records.py

Fixes the instance parameter in the records EDA source plugin example
records

fix eda plugin example

---

.github/workflows/integration_source.yml
.github/workflows/unit_source.yml
README.md
changelogs/fragments/508-drop-217.yml

Drop 2.17 from test matrix; add 2.19 to unit tests

Drop ansible-core 2.17; ensure ansible-core 2.19 in unit tests
