ansible-collections/servicenow.itsm

- .gitignore
- Makefile
- docs/integration_testing.md
- tests/integration/integration_config.yml.template
- tests/integration/targets/api_authentication/tasks/main.yml
In this PR, we prepare the initial directory hierarchy for running role-based integration tests with `ansible-test integration` and provide the first test target, `api_authentication`. We also add some documentation that explains how to get integration tests up and running, and the guidelines for writing integration tests.
For now, the integration tests can be run locally, with the help of new `make` targets.
Fixes #12.
> Initial integration testing setup & tests

- docs/module_template.md
- docs/unit_testing.md
- plugins/module_utils/client.py
- plugins/module_utils/table.py
- plugins/modules/change_request_info.py
- plugins/modules/incident_info.py
- plugins/modules/problem_info.py
- tests/unit/plugins/conftest.py
- tests/unit/plugins/module_utils/test_client.py
- tests/unit/plugins/module_utils/test_table.py
- tests/unit/plugins/modules/test_change_request_info.py
- tests/unit/plugins/modules/test_incident_info.py
- tests/unit/plugins/modules/test_problem_info.py
Table client adds another abstraction layer between the module's code and ServiceNow API. It serves the same purpose as the table helper functions we used before, but it better encapsulates the behavior, which makes testing things a lot easier.
> Add table client

- plugins/module_utils/utils.py
- tests/unit/plugins/module_utils/test_utils.py
Because certain values that ServiceNow API returns are far from human-readable. In order to get around this problem, we created a two-way mapping helper that we can use to transform module parameters into ServiceNow API payloads and back.
~Depends on #14~
> Add payload mapper

- plugins/module_utils/table.py
- tests/unit/plugins/module_utils/test_table.py
Right now, we only try to retrieve users by their `user_name` field, but there is nothing preventing us from expanding the list of lookup fields in the future.
> Add user lookup utility function

- plugins/modules/incident.py
* While closing incident user need to provide
`close_notes` and `close_code`
plugins/modules/incident.py
> incident: Update closed example

- plugins/module_utils/client.py
- tests/unit/plugins/module_utils/test_client.py
ServiceNow's API often returns valuable information in its error responses that can help users resolve issues and report bugs.
Up until now, we discarded this information and relied on status codes, which has obvious downsides. Changes in this commit rectify the situation and improve the ergonomics of the issue resolution process.
> Expose API error responses to playbook users

- plugins/inventory/now.py
- tests/unit/plugins/inventory/test_now.py
Resolves #2.
The inventory plugin adds hosts from records of the specified ServiceNow table. The users can customize which table
to query, which columns to retrieve as hostvars, and what columns should be used for `ansible_host` and inventory hostname.
By default, the plugin queries `cmdb_ci_server` table and uses the column `ip_address` as `ansible_host`. For inventory hostnames, the plugin uses the `name` column. It retrieves columns `name`, `host_name`, `fqdn`, `ip_address`, and adds them as host vars.
Inventory groups can be either auto-generated or specified explicitly (but not both):
* **Auto-generated groups**. By default, or when using a `group_by` configuration options, groups are created automatically based on the values of the provided columns. If no columns are specified, the …
> Add initial inventory plugin

- plugins/module_utils/problem.py
- plugins/module_utils/validation.py
- plugins/modules/problem.py
- plugins/modules/problem_info.py
- tests/integration/targets/problem/tasks/main.yml
- tests/unit/plugins/module_utils/test_validation.py
- tests/unit/plugins/modules/test_problem.py
Resolves #6.
In its current form, the new problem module has an issue when changing the state of an existing problem record to `resolved` or `closed`:
* When changing the state of a problem to `resolved`, state transition succeeds at the ServiceNow backend side (`state`
field is updated accordingly), yet the backend does not set the desired `resolution_code`.
* When changing the state of a problem to `closed`, we get a  403 response indicating that the field `resolution_code`
is missing from the request, despite being present.
Due to these unresolved issues, we temporarily disable a couple of checks in the integration tests for the module.
> Problem module

- plugins/doc_fragments/instance.py
- plugins/inventory/now.py
- plugins/module_utils/arguments.py
- plugins/module_utils/client.py
- tests/integration/targets/misc/tasks/main.yml
We add a new `timeout` parameter to the shared `instance` configuration.
This new parameter is exposed to all the modules in the collection, and to the inventory plugin. For consistency with other instance parameters, we allow setting the parameter either directly, or via the environment variable, `SN_TIMEOUT`.
> Add timeout parameter to instance configuration

- plugins/module_utils/client.py
- plugins/module_utils/validation.py
- tests/unit/plugins/module_utils/test_client.py
- tests/unit/plugins/module_utils/test_validation.py
When we developed things initially, we missed some compatibility spots (our unit tests cannot catch those, and because we do not have a CI/CD that would run integration tests on Python 2, those errors slipped through the cracks of manual testing).
> Make sure our code works on Python 2

- plugins/module_utils/utils.py
- plugins/modules/change_request.py
- plugins/modules/change_request_info.py
- plugins/modules/configuration_item.py
- plugins/modules/configuration_item_info.py
- plugins/modules/incident.py
- plugins/modules/incident_info.py
- plugins/modules/problem.py
- plugins/modules/problem_info.py
- tests/unit/plugins/module_utils/test_utils.py
Fixes #41.
Until now, our modules crashed when encountering unknown values for enumerated payload fields that are mapped between ServiceNow values and their canonical representations. 
In this PR, we fix this by ensuring that:
* Unknown values are included in their original form;
* Users are warned about specific values that our modules consider unknown via `module.warn`.
Example of a warning:
```
TASK [configuration_item : Retrieve a record with unknown install_status value] **********************************************************************************************************************************************************
[WARNING]: Encountered unknown value 999 while mapping field install_status.
ok: [testhost]
```
> Handle and warn about unknown values for enumerated payload fields

- tests/integration/targets/incident/tasks/main.yml
Parts of incident integration tests were commented out because our modules did not know how to handle unknown mapped values. Now that we added the required functionality to handle those cases, we can safely enable the problematic parts of the test.
> Run all incident integration tests

- plugins/inventory/now.py
- tests/integration/targets/inventory/files/group_by.now.yml
- tests/integration/targets/inventory/files/named_groups.now.yml
- tests/integration/targets/inventory/files/trivial.now.yml
- tests/integration/targets/inventory/playbooks/group_by.yml
- tests/integration/targets/inventory/playbooks/named_groups.yml
- tests/integration/targets/inventory/playbooks/trivial.yml
- tests/integration/targets/inventory/runme.sh
- tests/unit/plugins/inventory/test_now.py
The main purpose of this PR is to rename the `group` configuration option into `named_groups` to avoid clashing with the constructed inventory that is part of Ansible and may be added to the plugin in the future.
The remaining commits just refactor inventory code a bit and add unit tests for the functionality.
> Inventory updates

- changelogs/fragments/refresh_token.yml
- docs/servicenow.itsm.change_request_info_module.rst
- docs/servicenow.itsm.change_request_module.rst
- docs/servicenow.itsm.configuration_item_info_module.rst
- docs/servicenow.itsm.configuration_item_module.rst
- docs/servicenow.itsm.incident_info_module.rst
- docs/servicenow.itsm.incident_module.rst
- docs/servicenow.itsm.problem_info_module.rst
- docs/servicenow.itsm.problem_module.rst
- docs/servicenow.itsm.servicenow.itsm.now_inventory.rst
- plugins/doc_fragments/instance.py
- plugins/module_utils/arguments.py
- plugins/module_utils/client.py
- tests/integration/targets/api_authentication/tasks/main.yml
Fixes #63 
This introduces two new parameters, `grant_type` and `refresh_token`, in order to support additional OAuth login cases as described in the above issue.
module_utils
One issue I had while writing this is that to maintain backwards compatibility, `grant_type` has to default to `password`. This could be written more cleanly in a backwards-incompatible release.
> Add support for OAuth refresh token logins

- plugins/module_utils/query.py
- tests/integration/targets/change_request/tasks/main.yml
- tests/integration/targets/configuration_item/tasks/main.yml
- tests/integration/targets/incident/tasks/main.yml
- tests/integration/targets/problem/tasks/main.yml
- tests/unit/plugins/module_utils/test_query.py
Update on query module utils for unary operators
as they do not take any arguments.
https://docs.servicenow.com/bundle/quebec-platform-user-interface/page/use/common-ui-elements/reference/r_OpAvailableFiltersQueries.html
> Update on query module utils for unary operators

- tests/integration/targets/change_request/tasks/main.yml
- Fix `change_request` creation integration tests to test against the correct result
`change_request`
- Create test change_request (not the check mode one) results never got tested/checked since the task outputs its state in a different variable called `test_result` for later use. The module now copies that value into the `result` var before the test happens to fix that.
> Fix change_request creation tests to test against the correct result

- changelogs/fragments/change-request-change-on-hold-validation.yaml
- plugins/modules/change_request.py
- tests/integration/targets/change_request/tasks/main.yml
- Fix `change_request` `hold_reason` requirement
- Add integration tests for setting `change_request` `on_hold` without a `hold_reason`
`change_request`
- The `change_request` module now validates `on_hold` with its respective field instead of a non-existent `on_hold` `state` when requiring a `hold_reason`
- Added an integration test to cover on-hold management requirements (sets on_hold to true without a reason and checks the module's response)
> Bugfix change_request validation

- plugins/modules/configuration_item_info.py
Remove a redundant variable initialization as it gets overwritten in every case in the following lines.
Configuration item
> Remove redundant "query" variable initialization

- plugins/action/configuration_item_batch.py
- plugins/modules/configuration_item_batch.py
- tests/integration/targets/configuration_item_batch/tasks/main.yml
- tests/unit/plugins/action/test_configuration_item_batch.py
- tests/unit/plugins/modules/test_configuration_item_batch.py
This module allows updating a large number of CMDB entries.
The module is split up into two components: the action plugin that takes care of the mapping and the module which iterates over transformed data and updates the ServiceNow CMDB entries.
Fixes https://github.com/ansible-collections/servicenow.itsm/issues/88
> Add bulk update CMDB module

- tests/unit/plugins/action/test_configuration_item_batch.py
When we initially added tests for the batch module, we got one of the assert conditions wrong. This small PR fixes that issue and make sure our test actually performs a check.
> Update broken assertion in one of the unit tests

- galaxy.yml
- plugins/inventory/now.py
- plugins/modules/configuration_item_batch.py
Since we did not break the backward compatibility, we do not have to bump the major version in the upcoming release as we originally planned.
> Set version to 1.2.0

- changelogs/fragments/deprecate_non_constructed_inventory_features.yaml
- plugins/inventory/now.py
With the introduction of the constructed features to the inventory plugin, a lot of existing functionality is not needed anymore since it can be replaced by the constructed features.
This commit marks options that control the obsolete functionality as deprecated. The inventory plugin will also print a warning if it detects deprecated features being used since Ansible has some issues printing deprecation notices from plugins that are lazy-loaded.
> Deprecate duplicated inventory options

- plugins/modules/configuration_item_batch.py
Looking current code configuration_item_batch does not support
delete operation.
Update the docs to not to advertise this.
plugins/modules/configuration_item_batch.py
> configuration_item_batch: Update docs

- changelogs/fragments/client-change-base-path.yaml
- plugins/module_utils/attachment.py
- plugins/module_utils/client.py
- plugins/module_utils/table.py
- tests/unit/plugins/module_utils/test_attachment.py
- tests/unit/plugins/module_utils/test_client.py
- tests/unit/plugins/module_utils/test_table.py
ServiceNow Update Sets allow for extending the functionality of ServiceNow by, for example, obtaining and formatting results from joined tables. Through the ServiceNow REST API the records from Update Sets can be programmatically obtained. Currently, in the HTTP client it is assumed that all API endpoints start with base path `/api/now`, which might not be true in case of Updated Sets or in general when the requests might refer to the records outside namespace `now`.
This update removes the assumption about the base URL path from the HTTP client, by accepting any path, which makes it more generic. While it does not directly address any issue, it shall be seen as a prerequisite to issue #108, the resolution of which can be done by using a particular Updated Set, which is accessible on URL …
> Remove assumed /api/now base path from the HTTP client

- plugins/module_utils/utils.py
Mapping is defined in module definition and is optional. In case that it
is not listed in playbook it has default value None, which was not covered.
Case that it is not in dictionary or partial was allready covered.
Mapping
```paste below
```
> Bugfix - mapping may be None

- changelogs/fragments/enhanced-inventory.yaml
- plugins/inventory/now.py
- plugins/module_utils/relations.py
- tests/unit/plugins/inventory/test_now.py
- tests/unit/plugins/module_utils/test_relations.py
Extends inventory plugin module with groups extracted from CMDB relations.
Addresses issue #108.
Changes to `now`, added `relations` module utilities.
To enable this extension, add option `enhanced: true` to the inventory file.
Unlike the implementation from the old, deprecated repository, which required installation of an update set, this implementation obtains all the required data through ServiceNow REST API.
> Enhance inventory with groups from CMDB relations

- README.md
- changelogs/fragments/validate.yml
- docs/servicenow.itsm.now_inventory.rst
- plugins/inventory/now.py
* Developer can now validate parameters for plugins using
ansible-test sanity --test validate-modules
Fix errors provided by this check.
README.md
changelogs/fragments/validate.yml
> Fix validate-modules errors

- changelogs/fragments/inventory_grant.yaml
- plugins/inventory/now.py
now.py inventory plugin updated to support refresh_token and added in grant_type
Adds in support for refresh_token to now.py  inventory plugin
Fixes #168 
now.py inventory plugin
Before Change:
`ansible-inventory -i ~/git/tower-snow/inv/service_now.yml --list`
```
ansible-inventory 2.9.27
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /bin/ansible-inventory
python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/git/tower-snow/inv/token_service_now.yml as it did …
```
> now.py inventory plugin updated to support refresh_token and added in grant_type

- changelogs/fragments/now_inv_docs.yaml
- docs/servicenow.itsm.now_inventory.rst
Propose an update to now Inventory plugin docs to give examples of how AND OR queries operate.
Update adds 2 examples to the docs one for and AND query and one for an OR query.
now.py inventory plugin
This was something I required to do some trial and error for to get working and thought it would be helpful to share in the official documents.
Before this change there was no examples of using an AND or an OR query.  Added to give clarity to other users in the future.
```
plugin: servicenow.itsm.now
query:
- ip_address: NOT LIKE 192.29.32
name: STARTSWITH lnux
plugin: servicenow.itsm.now
query:
- ip_address: NOT LIKE 192.29.32
- name: STARTSWITH lnux
```
> Propose an update to now Inventory plugin docs to give examples of how AND OR queries operate

- changelogs/fragments/attachments.yaml
- plugins/module_utils/attachment.py
- plugins/modules/attachment.py
- tests/integration/targets/attachment/tasks/main.yml
- tests/unit/plugins/module_utils/test_attachment.py
- tests/unit/plugins/modules/test_attachment_module.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1591
A module that users can use to download attachments to specified file using attachment's sys_id.
Fixes #107 
Added:
- plugins/modules/attachment.py
- tests/unit/plugins/modules/test_attachment_module.py
Updated: 
- plugins/module_utils/attachment.py
- tests/unit/plugins/module_utils/test_attachment.py
- tests/integration/targets/attachment/tasks/main.yml
> attachment: A module to download attachment using sys_id

- changelogs/fragments/188_control_sysparm_display_value_in_info_modules.yml
- plugins/doc_fragments/sysparm_display_value.py
- plugins/module_utils/arguments.py
- plugins/module_utils/utils.py
- plugins/modules/change_request_info.py
- plugins/modules/change_request_task_info.py
- plugins/modules/configuration_item_info.py
- plugins/modules/incident_info.py
- plugins/modules/problem_info.py
- plugins/modules/problem_task_info.py
- tests/unit/plugins/modules/test_change_request_info.py
- tests/unit/plugins/modules/test_change_request_task_info.py
- tests/unit/plugins/modules/test_configuration_item_info.py
- tests/unit/plugins/modules/test_incident_info.py
- tests/unit/plugins/modules/test_problem_info.py
- tests/unit/plugins/modules/test_problem_task_info.py
This PR resolves #155 by providing additional module parameter `sysparm_display_value` to all "`*_info`" modules. 
For detailed description on why `sysparm_display_value` is needed, please refer to https://github.com/ansible-collections/servicenow.itsm/issues/155#issuecomment-1190992547. Also, [ServiceNow's docs regarding sysparm_display_value](https://docs.servicenow.com/en-US/bundle/sandiego-platform-administration/page/administer/exporting-data/concept/query-parameters-display-value.html) is relevant to understand how the query if changed if setting this attribute to either `true`, `false` or `all`.
Also, changes in `PayloadMapper` were made by adding additional field `sysparm_display_value`, which, if set to either `true` or `all`, does not use mapper as mapper basically maps …
> Control sysparm_display_value behavior in *_info modules

- sanity.requirements
Fix error for sanity check
after this click version has been forced I could run sanity checks, rigth now workin with this env.
```
ansible-base==2.10.17
black==21.12b0
cffi==1.15.1
click==8.0.4
cryptography==37.0.4
flake8==5.0.4
Jinja2==3.1.2
MarkupSafe==2.1.1
mccabe==0.7.0
mypy-extensions==0.4.3
packaging==21.3
pathspec==0.9.0
platformdirs==2.5.2
pycodestyle==2.9.1
pycparser==2.21
pyflakes==2.5.0
pyparsing==3.0.9
PyYAML==6.0
tomli==1.2.3
typing-extensions==4.3.0
```
> force click==8.0.4 to fix sanity check error, fix #196

- changelogs/fragments/adapt_attachment_integration_tests.yml
- tests/integration/targets/attachment/tasks/main.yml
Since PR 192 implements name as a unique identifier in configuration_item module, existing attachment integration test needed to be updated for the following configuration_item integration test to pass. Deletion of the configuration item was added at the end of the attachment integration test.
Attachment integration test (main.yml)
> Adapt integration tests for attachment module due to changes on PR 192 (configuration item idempotency)

- changelogs/fragments/190_add_alternative_way_to_filter_results.yml
- plugins/doc_fragments/query.py
- plugins/inventory/now.py
- plugins/module_utils/arguments.py
- plugins/modules/change_request_info.py
- plugins/modules/change_request_task_info.py
- plugins/modules/configuration_item_info.py
- plugins/modules/incident_info.py
- plugins/modules/problem_info.py
- plugins/modules/problem_task_info.py
- tests/unit/plugins/modules/test_change_request_info.py
- tests/unit/plugins/modules/test_change_request_task_info.py
- tests/unit/plugins/modules/test_configuration_item_info.py
- tests/unit/plugins/modules/test_incident_info.py
- tests/unit/plugins/modules/test_problem_info.py
- tests/unit/plugins/modules/test_problem_task_info.py
This PR enhances `*_info` modules and inventory plugin by adding additional attribute `sysparm_query`, which may be filled out by exporting environment variable `SN_SYSPARM_QUERY`.  `sysparm_query` is an alternative way to filter out the query results to `query` from before.
This PR resolved https://github.com/ansible-collections/servicenow.itsm/issues/102.
`servicenow.itsm.now` && `servicenow.itsm.*_info` modules.
> Enhance `servicenow.itsm.now` and `servicenow.itsm.*_info` modules by adding alternative way to filter out the results

- changelogs/fragments/71_configuration_item_implement_idempotence.yml
- plugins/modules/configuration_item.py
- plugins/modules/configuration_item_info.py
- tests/integration/targets/configuration_item/tasks/main.yml
- tests/unit/plugins/modules/test_configuration_item.py
- tests/unit/plugins/modules/test_configuration_item_info.py
Currently, the sys_id is the only parameter used to determine if we should be operating on one of the existing records or create a new one. In this PR the name parameter is added to also serve as a unique identifier of the record. As a consequence, it is impossible to insert two different CMDB items with the same name using Ansible. This breaks a task where a new record is created using existing name in CMDB. Instead, an existing record is updated (as opposed to before when a new record was created).
Accordingly, `configuration_item_info` module was updated with option "name".
Fixes #71 
Bugfix Pull Request
`servicenow.itsm.configuration_item`
`servicenow.itsm.configuration_item_info`
Also updated unit and integration tests for the modules
Running the task:
```yaml
- name: update CMDB …
```
> Configuration_item module: implement idempotence (issue #71)

- changelogs/fragments/test_api_remove_unused_import.yml
- tests/unit/plugins/modules/test_api.py
From test_api.py removed unused import which caused sanity error.
Bugfix Pull Request
test_api.py
> Fix sanity error in test_api

- changelogs/fragments/problem_management.yaml
- plugins/module_utils/problem.py
- plugins/module_utils/utils.py
- plugins/modules/problem.py
- tests/integration/targets/problem/tasks/main.yml
- tests/integration/targets/problem_with_mapping/tasks/main.yml
- tests/unit/plugins/conftest.py
- tests/unit/plugins/module_utils/test_problem.py
- tests/unit/plugins/modules/test_problem.py
Works around ServiceNow's limitation introduced in recent releases (starting with Rome) which made problem state transitioning with Table API impossible.
Fixes #163, #27 and #93.
- `module_utils/problem.py` - Added problem client for requesting problem state updates from _API for Red Hat Ansible Automation Platform Certified Content Collection_ Scripted REST API Service.
- `module_utils/util.py` - Added optional Boolean parameter `implicit` to `get_mapper` function to provide the default values for missing keys in the mapping.
- `modules/problem.py` - Added optional module parameter `base_api_path` to control the URI prefix of the endpoint exposed by _API for Red Hat Ansible Automation Platform Certified Content Collection_ Scripted REST API Service.
- …
> Fix problem state transition bug by using API for Red Hat Ansible Automation Platform Certified Content Collection

- changelogs/fragments/inventory_plugin_bugfix.yml
- plugins/inventory/now.py
Sysparm_query value was not used because of a bug. End result was, that whole cmdb table was returned in that case.
Inventory plugin
```paste below
```
> Bugfix: sysparm_query is now used inside request

- changelogs/fragments/api_query_params.yml
- plugins/module_utils/api.py
- plugins/module_utils/table.py
- plugins/modules/api.py
- tests/integration/targets/api/tasks/main.yml
Introduction of query_params as proposed inside #221. Since this is a generic api, we need to
support query parameters somewhere. 
History on #222, on which PR started from incorrect repository.
api
```paste below
```
> Api query params

- changelogs/fragments/inventory_plugin_reference_fields.yml
- plugins/inventory/now.py
- tests/integration/targets/inventory/files/reference_fields.now.yml
- tests/integration/targets/inventory/playbooks/reference_fields.yml
Inside this plugin we manually enable dot walking. Because service now allows returned values to have dot in names.
Fixes #231 
inventrory plugin
```paste below
```
> Enable lookups for dot walking

- plugins/modules/api_info.py
- plugins/modules/problem_task.py
api_info:
Attribute display_value: true was implicitly casted to bool and back to str resulting in value sent to API beeing "True" instead of "true".
problem_task:
Close code was missing.
api_info,  problem_task
```paste below
```
> Fixed two examples

- changelogs/fragments/client_validate_certs.yaml
- plugins/doc_fragments/instance.py
- plugins/module_utils/arguments.py
- plugins/module_utils/client.py
- tests/unit/plugins/module_utils/test_arguments.py
- tests/unit/plugins/module_utils/test_client.py
This PR adds validate_certs instance option to avoid error when using self-signed certificate as reported in issue #258.
module_utils.arguments.py
module_utils.client.py
doc_fragments.instance.py
Closes #258
> Certificate validation option

- changelogs/fragments/attachment_upload_module_bugfix.yml
- plugins/doc_fragments/attachments.py
- plugins/module_utils/attachment.py
- plugins/modules/attachment_upload.py
- tests/integration/targets/attachment_upload/tasks/main.yml
- tests/unit/plugins/module_utils/test_attachment.py
- tests/unit/plugins/modules/test_attachment_upload.py
The module wasn't working properly as reported in issue #259. This fix now solves the issue. 
attachment_upload module
> Attachment upload module bugfix

- changelogs/fragments/client_access_token.yaml
- plugins/doc_fragments/instance.py
- plugins/module_utils/arguments.py
- plugins/module_utils/client.py
- tests/integration/targets/api_authentication/tasks/main.yml
- tests/unit/plugins/module_utils/test_client.py
Added option to pass OAuth2 access token for authentication, previously obtained from ServiceNow.
Closes #255.
Modifies:
- `plugins/doc_fragments/instance.py`
- `plugins/module_utils/arguments.py`
- `plugins/module_utils/client.py`
- `tests/integration/targets/api_authentication/tasks/main.yml`
- `tests/unit/plugins/module_utils/test_client.py`
Previously, `grant_type` has had the default value `password` in the argument specification. This PR removes the default option from the argument specification, but maintains backwards compatibility by setting the default value internally.
```
> Added option to pass OAuth2 access token

- changelogs/fragments/cclose_code.yml
- plugins/doc_fragments/incident_mapping.py
- plugins/module_utils/arguments.py
- plugins/module_utils/incident.py
- plugins/modules/incident.py
- tests/integration/targets/incident/tasks/main.yml
- tests/integration/targets/incident_with_mapping/tasks/main.yml
* Removed hardcoding of parameter choices in close_code
* Allow incident_mapping for close_code so user can provide
custom choices.
> incident: allow incident_mapping for close_code

- changelogs/fragments/now_env_sysparm_query.yml
- plugins/inventory/now.py
Fixes: #293 
SN_SYSPARM_QUERY env variable is not picked up by e.g. inventory plugin now.py
```paste below
```
> Add missing env to docs for sysparm_query

- changelogs/fragments/configuration_item_info_return_fields.yml
- plugins/modules/configuration_item_info.py
add return_fields parmeter to the configuration_item_info module, needed for choose only needed information   It will speed considerably the response. and the returned data to process. It will be needed to build data maintentance proceses with heavily loaded classes. 
Implements #100 
configuration_item_info
Consider a data process to update info only some ci's with operational_status="opeational" , you need first query the complete class and after do something in a loop with the sys_id of each CI.
```yaml
- name: get info
servicenow.itsm.configuration_item_info:
sys_class_name: cmdb_ci_appl_ora_tns
return_fields:
- name
- sys_id
- operational_status
register: result
- name: Debug info
debug:
var: result
```
Time taken  to execute this playbook with "return_fields" …
> add return_fields parmeter to the configuration_item_info module

- tests/integration/targets/change_request/tasks/main.yml
- tests/integration/targets/change_request_task/tasks/main.yml
This PR fixes change_request and change_request_task integration tests on **Utah**.
Changes:
- makes the tests independent of the state of the db. Initially, the tests assumed some _change_requests_ exist already in db.
- clean up the resources created for the tests
Fixes _change_request_ and _change_request_task_ integration tests.
The tests had been executed on **Utah** release.
> Fix change_request and change_request_task int tests

- tests/integration/targets/api/tasks/main.yml
This commit randomizes the username used in integration tests for `api` module.
If the test cannot remove the created username, the test will fail on the next run.
> Make username creation idempotent in api module integration test

- changelogs/fragments/table_client.yml
- plugins/module_utils/table.py
- tests/unit/plugins/module_utils/test_table.py
When fetching records by sys_id that do not exist, the response body has no `results` key.
This PR adds a test for key existence before returning the content of results.
Fixes expectation `KeyError` when record not found by `sys_id`
table_client
```
curl -s "https://$instance/api/now/table/incident/bad-sys-id" --header "Accept:application/json" --user "admin":$PASS | jq
{
"error": {
"message": "No Record found",
"detail": "Record doesn't exist or ACL restricts the record retrieval"
},
"status": "failure"
}
```
> Fix 'KeyError' exception when trying to get by sys_id non existent record

- changelogs/fragments/api.yml
- plugins/module_utils/api.py
- plugins/modules/api.py
- tests/unit/plugins/modules/test_api.py
This PR replaces `get_record` call with `get_record_by_sys_id` in `update` and `delete` methods of `api` module.
This change will allow the `api` module to call other APIs than `Table API`. 
api module
Follow up to #306
> Replace `get_record` by `get_record_by_sys_id` for update and delete op in api module

- changelogs/fragments/client_object_hook.yml
- plugins/module_utils/client.py
- tests/unit/plugins/module_utils/test_client.py
This commit allows the user to pass a `object_hook` function to client for custom decoding the json response from SNow.
It will be used to fix **Change Management API** response.
Fixes #305 
> Allow passing a object_hook to rest client

- changelogs/fragments/api.yml
- changelogs/fragments/api_info.yml
- plugins/module_utils/api.py
- plugins/module_utils/client.py
- plugins/module_utils/generic.py
- plugins/module_utils/snow.py
- plugins/module_utils/table.py
- plugins/modules/api.py
- plugins/modules/api_info.py
- tests/integration/targets/api_generic/tasks/main.yml
This PR adds a new client that can access services outside "/table" namespace.
A new client, on top of the rest client, has been added to add the functionality of snow services. This is needed because the snow services don't have the same behavior.
For example, the `Table API` server puts the total items in the custom header `x-total-count` where others don't.
The high-level clients `TableClient` and `GenericClient` inherit this client.
A new field `api_path` is added in the modules `api` and `api_info` to choose between `TableClient` or `GenericClient`.
`api_path` is mutually exclusive with `resource` which refers to a table in `Table API`.
```
- name: Create test ci - check mode
servicenow.itsm.api:
api_path: "api/now/cmdb/instance/cmdb_ci_linux_server"
action: post
data:
attributes: …
```
> Add generic client

- changelogs/fragments/change_request_category.yml
- plugins/doc_fragments/change_request_mapping.py
- plugins/module_utils/arguments.py
- plugins/module_utils/change_request.py
- plugins/modules/change_request.py
- tests/integration/targets/change_request/tasks/main.yml
- tests/integration/targets/change_request_with_mapping/tasks/main.yml
- tests/integration/targets/inventory/files/reference_fields.now.yml
This PR removes the hard coding of choices of category and allows mapping for the category so user can provide custom values
Fixes #266 
`change_request`
> Remove hard coding of choices of category in change_request

- tests/integration/targets/api/tasks/main.yml
- tests/integration/targets/configuration_item/tasks/main.yml
This PR makes the integration tests for `api` and `configuration_item` independent from the initial data of the test instance
> Isolate `api` and `configuration_item` tests from initial instance data

- changelogs/fragments/no_dot_var.yml
- plugins/inventory/now.py
- tests/integration/targets/inventory/files/no_dot_var.now.yml
- tests/integration/targets/inventory/playbooks/no_dot_var.yml
The reference field columns are imported host variables with a "." in the name.  It is not a valid Ansible variable name.  This created problem in Ansible.  For exmample,  we can't use the host variable in constructed inventory.
This can be work around by creating composed variables.  However, since name with "." is not a valid Ansible variable name, we should just replace during import.
This change replace "." with underscore "_"
Inventory plugin
For example, columns defined in now.yml
```paste below
columns:
- location.name
- support_group.name
- u_my_reference_table.u_my_reference_column
```
will be imported as host variables
```
location_name
support_group_name
u_my_reference_table_u_my_reference_column
```
> feature/no_dot_var - Replace "." in column name to "_"

- .github/workflows/all_green_check.yml
Use different workflow target to enable integration tests to run
Github workflow
The existing trigger system cannot run the integration tests because they require secrets and those are not provided to forked repo PRs. This is github's mechanism to work around that. It also includes the addition of a new workflow, which requires the label "safe to test" applied to a PR to allow integration tests to run.
> Update workflow to allow integration tests to run with maintainer approval

- .github/workflows/integration_source.yml
Matricize integration tests
This is to take advantage of the new test instances we are soon going to acquire, allowing us to test against multiple versions of ServiceNow in parallel.
GitHub workflows
The challenge here was to use specific secrets for each servicenow release, as the integration tests are tied to a specific instance. Details on how to do this can be found here: https://github.com/orgs/community/discussions/26302
```paste below
```
> Matricize ServiceNow tests and make variable passing shell-safe

- plugins/module_utils/snow.py
- tests/unit/plugins/modules/test_configuration_item_relations.py
This PR fix crashes when calling endpoints that don't have `x-total-count` in the header.
snow.py
> Fix crash when the "x-total-count" is not found in header

- tests/integration/targets/change_request/tasks/main.yml
- tests/integration/targets/change_request_task/tasks/main.yml
- tests/unit/plugins/module_utils/test_cmdb_relations.py
Tests fail because multiple parallel executions use the same assignement_group on the same instance.
> Use a different assignement_group for each python/ansible combination

- tests/unit/plugins/module_utils/test_cmdb_relations.py
This PR fix lint failures due to using an older black version.
> Fix lint by using the right black version

- changelogs/fragments/inventory_timeout.yml
- plugins/inventory/now.py
- tests/unit/plugins/inventory/test_now.py
Fix crash when SN_TIMEOUT is set.
SN_TIMEOUT is passed as `string` instead of `float`.
Fixes AAP-23059
inventory
> Fix crash when SN_TIMEOUT is set

- .github/workflows/integration_source.yml
- changelogs/fragments/service_catalog_info.yml
- plugins/module_utils/service_catalog.py
- plugins/modules/service_catalog_info.py
- tests/integration/targets/service_catalog_info/tasks/main.yml
- tests/unit/plugins/module_utils/test_service_catalog.py
- tests/unit/plugins/modules/test_service_catalog_info.py
This PR adds a module to retrieve information about service catalog along with categories and items
This is part of Service Catalog features.
```paste below
- name: Return all catalogs without categories but with items (brief information)
servicenow.itsm.service_catalog_info:
categories: false
items_info: brief
- name: Return service catalog without categories but with items (brief information)
servicenow.itsm.service_catalog_info:
instance:
sys_id: "{{ service_catalog.sys_id }}"
categories: false
items_info: brief
- name: Return service catalog with categories and with items (full information)
servicenow.itsm.service_catalog_info:
instance:
sys_id: "{{ service_catalog.sys_id }}"
categories: true
items_info: full
```
> New module: service_catalog_info - to retrieve information about service catalog along with categories and items

- .github/workflows/integration_source.yml
- plugins/module_utils/service_catalog.py
- plugins/modules/service_catalog.py
- tests/integration/targets/service_catalog/tasks/main.yml
- tests/unit/plugins/modules/test_service_catalog.py
This PR adds a module to checkout cart or order items from service catalog
service_catalog
```paste below
- name: Create new mail
servicenow.itsm.service_catalog:
action: order_now
items:
- sys_id: "{{ result.records[0].sn_items[0].sys_id }}"
requested_for: abraham.lincoln
variables:
new_email: test@example.com
```
> New module: service_catalog: checkout cart, order_now items from service catalog

- tests/integration/targets/service_catalog/tasks/main.yml
To avoid clashes between test runs, a random user is created before running service catalog integration tests.
Fix service_catalog integration tests failures.
service_catalog tests
> Fix service_catalog integration tests by creating a random user

- .github/workflows/integration_source.yml
- .github/workflows/sanity.yml
- .github/workflows/unit_source.yml
- README.md
- changelogs/fragments/remove_tokyo.yml
Unit and Sanity tests fail on Python 3.10. Exclude it.
Tokyo is no longer supported by ServiceNow. Remove it.
Tests
> Filter Python 3.10 and Remove Tokyo

- .github/workflows/integration_source.yml
- .github/workflows/unit_source.yml
Now that stable-2.17 is out add it explicitly
Test workflow update
> Add stable-2.17 targets with Python 3.10 exclusions

- changelogs/fragments/release_summary.yml
Changelog and version number were not properly aligned. Cutting new release to fix.
> Add new release note to cover documentation problem

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add_xanadu.yaml
- changelogs/fragments/inventory_aggregation.yml
- changelogs/fragments/release_summary.yml
- docs/servicenow.itsm.api_info_module.rst
- docs/servicenow.itsm.api_module.rst
- docs/servicenow.itsm.attachment_info_module.rst
- docs/servicenow.itsm.attachment_upload_module.rst
- docs/servicenow.itsm.change_request_info_module.rst
- docs/servicenow.itsm.change_request_module.rst
- docs/servicenow.itsm.change_request_task_info_module.rst
- docs/servicenow.itsm.change_request_task_module.rst
- docs/servicenow.itsm.configuration_item_batch_module.rst
- docs/servicenow.itsm.configuration_item_info_module.rst
- docs/servicenow.itsm.configuration_item_module.rst
- docs/servicenow.itsm.configuration_item_relations_info_module.rst
- docs/servicenow.itsm.configuration_item_relations_module.rst
- docs/servicenow.itsm.incident_info_module.rst
- docs/servicenow.itsm.incident_module.rst
- docs/servicenow.itsm.now_inventory.rst
- docs/servicenow.itsm.problem_info_module.rst
- docs/servicenow.itsm.problem_module.rst
- docs/servicenow.itsm.problem_task_info_module.rst
- docs/servicenow.itsm.problem_task_module.rst
- docs/servicenow.itsm.service_catalog_info_module.rst
- docs/servicenow.itsm.service_catalog_module.rst
- galaxy.yml
> prepare 2.7.0 release

- changelogs/fragments/query_limiting.yml
- plugins/inventory/now.py
- tests/integration/targets/inventory/files/constructed_fail.now.yml
- tests/integration/targets/inventory/files/constructed_limit_additional.now.yml
- tests/integration/targets/inventory/files/constructed_limit_bare.now.yml
- tests/integration/targets/inventory/playbooks/constructed_fail.yml
- tests/integration/targets/inventory/playbooks/constructed_limit_additional.yml
- tests/integration/targets/inventory/playbooks/constructed_limit_bare.yml
Add a new parameter to limit queries to the database in inventory queries, inspired by @demonpig's approach
Fixes AAP-40052
Inventory plugin
Example usage:
This inventory would activate the query limiting feature by setting query_limit_columns to true. query_additional_columns need only list those columns that are not listed in the columns section; those will be included and the full list will be deduplicated before sending to the backend for processing.
The intention here is to limit the amount of data that the client must process when retrieving inventory data. This can be substantial. Note that the limiting of the query happens only when query_only_columns is specified; the default
behavior is to query the entire table as documentation examples and no doubt lots …
> Backward-compatible query limiting feature

- changelogs/fragments/435-update-unit-tests-for-2.19.yaml
- plugins/action/api.py
- plugins/modules/change_request_task.py
- tests/integration/generate_integration_config.sh
- tests/integration/targets/itsm_api/tasks/main.yml
- tests/integration/targets/itsm_change_request/tasks/main.yml
- tests/integration/targets/itsm_change_request_task/tasks/main.yml
- tests/integration/targets/itsm_change_request_with_mapping/tasks/main.yml
- tests/integration/targets/itsm_incident_with_mapping/tasks/main.yml
- tests/integration/targets/problem/tasks/main.yml
- tests/integration/targets/problem_with_mapping/tasks/main.yml
- tests/unit/plugins/common/utils.py
- tests/unit/plugins/inventory/test_now.py
- tests/unit/plugins/modules/test_api_info.py
- tests/unit/plugins/modules/test_attachment_info.py
- tests/unit/plugins/modules/test_attachment_upload.py
- tests/unit/plugins/modules/test_change_request_info.py
- tests/unit/plugins/modules/test_change_request_task_info.py
- tests/unit/plugins/modules/test_configuration_item.py
- tests/unit/plugins/modules/test_configuration_item_info.py
- tests/unit/plugins/modules/test_incident.py
- tests/unit/plugins/modules/test_incident_info.py
- tests/unit/plugins/modules/test_problem_info.py
- tests/unit/plugins/modules/test_problem_task_info.py
This change updates the unit tests to be compatible with ansible-core 2.19. It follows the recommendations [here](https://forum.ansible.com/t/data-tagging-preview-and-testing/40759) which indicate that the argument object expected by the module class has changed slightly
There are a few changes outside of the tests directory:
- For modules that accept a template instead of a data dict (seems limited to the api action plugin), the template must be explicitly marked as safe in 2.19+. This is done in the module to preserve the existing behavior
- For change_request_task, the module did not raise an error that is already documented as not allowed. The test to check for this error passed due to implicit boolean handling. 2.19 is more strict about when things evaluate to true, which caused the …
> fix unit tests for devel and 2.19

- .github/workflows/integration_source.yml
Exclude Python 3.9 from integration tests against 2.16 and 2.17
workflow
> Exclude 3.9 from 2.16 and 2.17 integration tests too

- .github/workflows/all_green_check.yml
- .github/workflows/nightly.yml
- changelogs/fragments/20250508-fix_nightly.yaml
Fix nightly CI run by splitting it into a separate workflow without safe-to-test requirement
workflows
> Fix nightly CI to not require safe-to-test

- changelogs/fragments/451-inventory-bugfix.yml
- plugins/inventory/now.py
Fixes https://github.com/ansible-collections/servicenow.itsm/issues/451
After re-factoring the inventory plugin function for the linters, it looks like there is a syntax issue that was not caught by the tests. This change should fix that.
inventory plugin
> fix inventory plugin syntax issue with fetch columns

- CHANGELOG.rst
- changelogs/changelog.yaml
- docs/servicenow.itsm.api_info_module.rst
- docs/servicenow.itsm.api_module.rst
- docs/servicenow.itsm.attachment_info_module.rst
- docs/servicenow.itsm.attachment_upload_module.rst
- docs/servicenow.itsm.change_request_info_module.rst
- docs/servicenow.itsm.change_request_module.rst
- docs/servicenow.itsm.change_request_task_info_module.rst
- docs/servicenow.itsm.change_request_task_module.rst
- docs/servicenow.itsm.configuration_item_batch_module.rst
- docs/servicenow.itsm.configuration_item_info_module.rst
- docs/servicenow.itsm.configuration_item_module.rst
- docs/servicenow.itsm.configuration_item_relations_info_module.rst
- docs/servicenow.itsm.configuration_item_relations_module.rst
- docs/servicenow.itsm.incident_info_module.rst
- docs/servicenow.itsm.incident_module.rst
- docs/servicenow.itsm.now_inventory.rst
- docs/servicenow.itsm.problem_info_module.rst
- docs/servicenow.itsm.problem_module.rst
- docs/servicenow.itsm.problem_task_info_module.rst
- docs/servicenow.itsm.problem_task_module.rst
- docs/servicenow.itsm.service_catalog_info_module.rst
- docs/servicenow.itsm.service_catalog_module.rst
- galaxy.yml
Fix prior release
Release
Release 2.9.1 is bad because the tag refers to the wrong commit. This will fix the previous release
> prepare 2.9.2 release

- plugins/module_utils/generic.py
This is currently trying to call `.get()` from a string, which causes the following to be raised:
```
AttributeError: 'str' object has no attribute 'get'
```
change_request
Try and update a change request task using Ansible, and you will get this error. With this change applied locally it updates the records with no issues.
> Call .get() from the dict, not the string

- plugins/inventory/now.py
The records list was not being updated after running __populate_records_from_remote() leading to no hosts being added.
Fixes #456 
now.py
> Obtain records after populating

- changelogs/fragments/460-add-test-vars-setup-role.yml
- tests/integration/targets/api_authentication/meta/main.yml
- tests/integration/targets/itsm_api/meta/main.yml
- tests/integration/targets/itsm_api_generic/meta/main.yml
- tests/integration/targets/itsm_attachment/meta/main.yml
- tests/integration/targets/itsm_attachment_info/meta/main.yml
- tests/integration/targets/itsm_attachment_upload/meta/main.yml
- tests/integration/targets/itsm_change_request/meta/main.yml
- tests/integration/targets/itsm_change_request_task/tasks/meta/main.yml
- tests/integration/targets/itsm_change_request_with_mapping/tasks/meta/main.yml
- tests/integration/targets/itsm_configuration_item/meta/main.yml
- tests/integration/targets/itsm_configuration_item_batch/tasks/meta/main.yml
- tests/integration/targets/itsm_configuration_item_relations/tasks/meta/main.yml
- tests/integration/targets/itsm_incident/meta/main.yml
- tests/integration/targets/itsm_incident_with_mapping/meta/main.yml
- tests/integration/targets/itsm_misc/meta/main.yml
- tests/integration/targets/itsm_service_catalog/meta/main.yml
- tests/integration/targets/itsm_service_catalog_info/meta/main.yml
- tests/integration/targets/prepare_test_vars/meta/main.yml
- tests/integration/targets/problem/meta/main.yml
- tests/integration/targets/problem_task/tasks/meta/main.yml
- tests/integration/targets/problem_with_mapping/meta/main.yml
This change adds a consistent setup role to all integration tests. This provides two main benefits
1. all tests will have the same authentication variables setup, checked, and available to them
2. a unique test ID is generated for all tests. This will ensure all tests have a consistent unique ID and can be made thread safe
I will open a second PR to ensure tests are thread safe and use the unique test ID when possible
tests/integration
> add test vars role dependency to all tests

- changelogs/fragments/465-use-unique-id-in-all-tests.yml
- tests/integration/targets/itsm_api/tasks/main.yml
- tests/integration/targets/itsm_attachment/tasks/main.yml
- tests/integration/targets/itsm_change_request_task/tasks/main.yml
- tests/integration/targets/itsm_configuration_item/tasks/main.yml
- tests/integration/targets/itsm_configuration_item_batch/tasks/main.yml
- tests/integration/targets/itsm_configuration_item_relations/tasks/main.yml
- tests/integration/targets/itsm_service_catalog/tasks/main.yml
- tests/integration/targets/problem/tasks/main.yml
- tests/integration/targets/problem_task/tasks/main.yml
- tests/integration/targets/problem_with_mapping/tasks/main.yml
Needs https://github.com/ansible-collections/servicenow.itsm/pull/464
This change makes all tests use the unique_test_id variable instead of calling the password lookup all over the place
tests/integration
> use unique_test_id in all tests instead of lookup

- .github/workflows/integration_source.yml
- changelogs/fragments/416-add-token-auth-method.yml
- changelogs/fragments/474-add-client-cred-support-inven.yml
- docs/servicenow.itsm.now_inventory.rst
- plugins/doc_fragments/instance.py
- plugins/inventory/now.py
- plugins/module_utils/arguments.py
- plugins/module_utils/client.py
- tests/integration/targets/api_authentication/tasks/main.yml
- tests/integration/targets/inventory/setup.yml
- tests/integration/targets/inventory/templates/api_key.now.yml
- tests/integration/targets/inventory/templates/client_cred_grant.now.yml
- tests/integration/targets/inventory/templates/underline_var.now.yml
- tests/integration/targets/inventory/tests/api_key.yml
- tests/integration/targets/inventory/tests/client_cred_grant.yml
- tests/integration/targets/inventory/tests/underline_var.yml
- tests/unit/plugins/module_utils/test_client.py
Added configurable token_auth_method parameter to support both x-sn-apikey and Authorization Bearer headers for access tokens
plugins/module_utils/arguments.py
plugins/module_utils/client.py
tests/integration/targets/api_authentication/tasks/main.yml
ests/unit/plugins/module_utils/test_client.py
Uses the API-key method as default, the User can choose Bearer method by stating: 
"token_auth_method": "bearer"
> Added configurable token_auth_method 

- changelogs/fragments/483-inven-enhanced-params.yml
- plugins/inventory/now.py
- tests/integration/targets/inventory/templates/enhanced.now.yml
- tests/integration/targets/inventory/tests/enhanced.yml
- tests/unit/plugins/inventory/test_now.py
This change allows users to modify how the `enhanced` option impacts the inventory plugin. It adds three new options:
`enhanced_additional_columns` - Include additional columns/attributes when querying the relationship table
`enhanced_query` - Specify a query that can be used to limit the relationships returned when `enhanced` is true
`enhanced_sysparm_query` - Same as `enhanced_query` but different format
Fixes https://github.com/ansible-collections/servicenow.itsm/issues/436
plugins/inventory/now
> Allow relationship filtering when using enhanced in inven plugin

- changelogs/fragments/489-add-enhanced-query-limit.yml
- plugins/inventory/now.py
- tests/integration/targets/inventory/templates/enhanced.now.yml
Adding an option to control the batch size of relationship queries, separate from other queries. This allows users to fine tune the relationship query performance without impacting the other inventory queries. 
now
> add option to tune relationship batches in inven

- .github/workflows/integration_source.yml
- changelogs/fragments/20250728-milestone.yml
Trivial change to swap out milestone in integration tests and add stable-2.19 in its place
- Trivial test changes
- 
Github Workflows
> Update testing matrix to add 2.19 and remove milestone
